package com.leucine.academiaportal.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing an Administrator's profile.
 * This entity is mapped to the 'administrator_profile' table in the database.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AdministratorProfile {

    /**
     * Primary key for the AdministratorProfile entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;

    /**
     * One-to-One relationship with the User entity.
     * The primary key of the User entity is also used as the foreign key here.
     */
    @OneToOne
    @MapsId
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * URL or path to the profile photo of the administrator.
     * This field is optional and can be null.
     */
    @Size(max = 255, message = "Photo URL or path must be less than 255 characters")
    private String photo;

    /**
     * Many-to-One relationship with the Department entity.
     * This field is used to associate the administrator with a specific department.
     */
    @ManyToOne
    @JoinColumn(name = "department_id")
    @NotNull(message = "Department cannot be null")
    private Department department;
}
