package com.leucine.academiaportal.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a course in the system.
 * This entity is mapped to the 'course' table in the database.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Course {

    /**
     * Primary key for the Course entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the course.
     * This field is required and cannot be blank.
     */
    @Column(nullable = false)
    @NotBlank(message = "Title cannot be blank")
    private String title;

    /**
     * Description of the course.
     * This field is optional and can be null.
     */
    private String description;

    /**
     * Department to which the course belongs.
     * This is a many-to-one relationship with the Department entity.
     */
    @ManyToOne
    @JoinColumn(name = "department_id")
    private Department department;

    /**
     * Faculty profile responsible for teaching the course.
     * This is a many-to-one relationship with the FacultyProfile entity.
     */
    @ManyToOne
    @JoinColumn(name = "faculty_id")
    private FacultyProfile faculty;
}
