package com.leucine.academiaportal.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a department in the system.
 * This entity is mapped to the 'department' table in the database.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Department {

    /**
     * Primary key for the Department entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the department.
     * This field is required and cannot be blank.
     */
    @Column(nullable = false, unique = true)
    @NotBlank(message = "Name cannot be blank")
    private String name;

    /**
     * Description of the department.
     * This field is optional and can be null.
     */
    private String description;
}