package com.leucine.academiaportal.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing an enrollment in a course.
 * This entity is mapped to the 'enrollment' table in the database.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Enrollment {

    /**
     * Primary key for the Enrollment entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Reference to the StudentProfile entity.
     * Establishes a many-to-one relationship where multiple enrollments can be associated with one student.
     */
    @ManyToOne
    @JoinColumn(name = "student_id", nullable = false)
    private StudentProfile student;

    /**
     * Reference to the Course entity.
     * Establishes a many-to-one relationship where multiple enrollments can be associated with one course.
     */
    @ManyToOne
    @JoinColumn(name = "course_id", nullable = false)
    private Course course;
}
