package com.leucine.academiaportal.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a student profile.
 * This entity is mapped to the 'student_profile' table in the database.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class StudentProfile {

    /**
     * Primary key for the StudentProfile entity.
     * Automatically generated by the database and corresponds to the 'user_id' column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;

    /**
     * Reference to the User entity.
     * Establishes a one-to-one relationship where each student profile is associated with a single user.
     */
    @OneToOne
    @MapsId
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * URL or path to the student's photo.
     */
    private String photo;

    /**
     * Reference to the Department entity.
     * Establishes a many-to-one relationship where multiple student profiles can be associated with one department.
     */
    @ManyToOne
    @JoinColumn(name = "department_id")
    private Department department;

    /**
     * The academic year of the student (e.g., "Sophomore", "Junior", "Senior").
     */
    private String year;
}
